services:
  cuda:
    build: .
    image: cuda-bench:latest

    runtime: nvidia
    working_dir: /workspace

    volumes:
      - ./:/workspace

    stdin_open: true
    tty: true

    command: /bin/bash